name: continous integration of python application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo from the scm
        uses: actions/checkout@v4.2.2
        
      - name: set up python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.9'
          
      # - name: Install dependencies
      #   run: |
      #     python -m venv venv
      #     source venv/bin/activate
      #     pip install --upgrade pip
      #     pip3 install Flask

      # - name: run test
      #   run:
      #     source venv/bin/activate
      #     pytest 

      - name: Build application
        run: python application.py sdist bdist_wheel

      - name: path
        run: mkdir staging && cp dist/*.whl staging

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.1
        with:
           name: Package
           path: staging 
    
